server:
  port: 12010
spring:
  application:
    name: food-service
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/load_food
    username: ENC(ibAzlLFZ16lQKqWIJ+wLkw==)
    password: ENC(cHBSMBrBlzdWpW1sfjMneQ==)
  jpa:
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
logging:
  level:
    root: info
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace

global:
  xClientKey: ${x_client_key}

jasypt:
  key: ${jasypt_key}